export const FETCH_USER = 'FETCH_USER';
export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const NEXT = 'NEXT';
export const CREATED_PLAYLIST_URL = 'CREATED_PLAYLIST_URL';
export const GET_CURRENTLY_PLAYING = 'GET_CURRENTLY_PLAYING';
