// fetch user
export const FETCH_USER = 'FETCH_USER';
// top tracks
export const FETCH_TOP_TRACKS_PENDING = 'FETCH_TOP_TRACKS_PENDING';
export const FETCH_TOP_TRACKS_SUCCESS = 'FETCH_TOP_TRACKS_SUCCESS';
export const FETCH_TOP_TRACKS_ERROR = 'FETCH_TOP_TRACKS_ERROR';
export const FETCH_TOP_TRACKS_HAS_MORE = 'FETCH_TOP_TRACKS_HAS_MORE';
// top artists
export const FETCH_TOP_ARTISTS_PENDING = 'FETCH_TOP_ARTISTS_PENDING';
export const FETCH_TOP_ARTISTS_SUCCESS = 'FETCH_TOP_ARTISTS_SUCCESS';
export const FETCH_TOP_ARTISTS_ERROR = 'FETCH_TOP_ARTISTS_ERROR';
export const FETCH_TOP_ARTISTS_HAS_MORE = 'FETCH_TOP_ARTISTS_HAS_MORE';
// recently played tracks
export const FETCH_RECENTLY_PLAYED_TRACKS_PENDING = 'FETCH_RECENTLY_PLAYED_TRACKS_PENDING';
export const FETCH_RECENTLY_PLAYED_TRACKS_SUCCESS = 'FETCH_RECENTLY_PLAYED_TRACKS_SUCCESS';
export const FETCH_RECENTLY_PLAYED_TRACKS_ERROR = 'FETCH_RECENTLY_PLAYED_TRACKS_ERROR';
export const FETCH_RECENTLY_PLAYED_TRACKS_HAS_MORE = 'FETCH_RECENTLY_PLAYED_TRACKS_HAS_MORE';
export const FETCH_RECENTLY_PLAYED_TRACKS_BEFORE = 'FETCH_RECENTLY_PLAYED_TRACKS_BEFORE';
// create a playlist
export const CREATE_PLAYLIST_PENDING = 'CREATE_PLAYLIST_PENDING';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_ERROR = 'CREATE_PLAYLIST_ERROR';
