// fetch user
export const FETCH_USER = 'FETCH_USER';
// top tracks
export const FETCH_TOP_TRACKS_PENDING = 'FETCH_TOP_TRACKS_PENDING';
export const FETCH_TOP_TRACKS_SUCCESS = 'FETCH_TOP_TRACKS_SUCCESS';
export const FETCH_TOP_TRACKS_ERROR = 'FETCH_TOP_TRACKS_ERROR';
export const FETCH_TOP_TRACKS_HAS_MORE = 'FETCH_TOP_TRACKS_HAS_MORE';
// top artists
export const FETCH_TOP_ARTISTS_PENDING = 'FETCH_TOP_ARTISTS_PENDING';
export const FETCH_TOP_ARTISTS_SUCCESS = 'FETCH_TOP_ARTISTS_SUCCESS';
export const FETCH_TOP_ARTISTS_ERROR = 'FETCH_TOP_ARTISTS_ERROR';
export const FETCH_TOP_ARTISTS_HAS_MORE = 'FETCH_TOP_ARTISTS_HAS_MORE';
// recently played
export const FETCH_RECENTLY_PLAYED = 'FETCH_RECENTLY_PLAYED';
export const HAS_MORE_RECENTLY_PLAYED_TRACKS = 'HAS_MORE_RECENTLY_PLAYED_TRACKS';
export const RECENTLY_PLAYED_BEFORE = 'RECENTLY_PLAYED_BEFORE';
// create a playlist
export const CREATED_PLAYLIST = 'CREATED_PLAYLIST';
